### PR TITLE
docs: var storage -> var gcs;

### LINKED ISSUE #619: Rename Storage examples from "var storage" to "var gcs"
Continues https://github.com/GoogleCloudPlatform/gcloud-node/pull/617#discussion-diff-30792128...

It seems a lot of people refer to "Cloud Storage" as "GCS" as opposed to "Storage". In userland, I've seen [`var gcs = gcloud.storage(/*...*/);`](https://github.com/GoogleCloudPlatform/gcloud-node/issues/522) more than once, and tend to prefer that name over the more generic "var storage;" naming.

Any thoughts on changing our Storage examples to use `var gcs = gcloud.storage();` in place of `var storage = gcloud.storage();`? The term "storage" feels vague to me, instead of implying that it offers functionality that sits above a bucket.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #619 

Docs: http://stephenplusplus.github.io/gcloud-node-gh-pages-again/#/

### CODE REVIEW

**Comment by ryanseys** [comment]
Will review

**Comment by jgeewax** [comment]
LGTM

**Comment by ryanseys** [comment]
You missed a few, one in the README and some throughout the tests. 

```
/Users/ryanseys/gcloud-node/README.md:
  175  // global basis (see Authorization section above).
  176  
  177: var storage = gcloud.storage({
  178    keyFilename: '/path/to/keyfile.json',
  179    projectId: 'my-project'

/Users/ryanseys/gcloud-node/system-test/bigquery.js:
   29  var gcloud = require('../lib')(env);
   30  var bigquery = gcloud.bigquery();
   31: var storage = gcloud.storage();
   32  
   33  describe('BigQuery', function() {

/Users/ryanseys/gcloud-node/system-test/storage.js:
   30  
   31  var env = require('./env.js');
   32: var storage = require('../lib/storage')(env);
   33  
   34  var BUCKET_NAME = generateBucketName();

/Users/ryanseys/gcloud-node/test/storage/file.js:
 1330  
 1331      beforeEach(function() {
 1332:       var storage = bucket.storage;
 1333        storage.makeAuthorizedRequest_.getCredentials = function(callback) {
 1334          callback(null, credentials);
 ....
 1530  
 1531      beforeEach(function() {
 1532:       var storage = bucket.storage;
 1533        storage.makeAuthorizedRequest_.getCredentials = function(callback) {
 1534          callback(null, credentials);

/Users/ryanseys/gcloud-node/test/storage/index.js:
   26  
   27  describe('Storage', function() {
   28:   var storage;
   29  
   30    beforeEach(function() {
```

**Comment by stephenplusplus** [comment]
I was going to leave the tests untouched, since the use of `var storage` makes more sense for us (the developers of this project) in the `Storage`->`storage` relationship.

Good catch on the readme.

**Comment by stephenplusplus** [comment]
Got the readme.

**Comment by ryanseys** [comment]
SGTM

**Pull request merged**
