### PR TITLE
fix(deps): bump `google-gax` to ^3.5.8

### LINKED ISSUE #4116: `taffydb` vulnerability in `google-gax` dependency chain
google-gax issue: https://github.com/googleapis/gax-nodejs/issues/1424

It has been fixed in version `3.5.6`

### PR DESCRIPTION
**Pull request by EduardoBautista**
Fixes dependency vulnerability in google-gax -> protobufjs-cli

Fixes #4116 🦕

### CODE REVIEW

**Comment by EduardoBautista** [comment]
I am uncertain if I am supposed to run `npm install` on each package individually. Please let me know what other changes I need to make to get this mergeable.

**Review by alexander-fenster — APPROVED** [review]

**Comment by alexander-fenster** [comment]
Thanks @EduardoBautista, I'll take it from here!

**Pull request merged**
