### PR TITLE
Nodejs GAPIC: Speech v1

### PR DESCRIPTION
**Pull request by lukesneeringer**
This pull request was generated by artman. Please review it thoroughly before merging.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Need those doc files.

**Comment by lukesneeringer** [comment]
The deletions of all of the doc files should not have happened.

**Comment by stephenplusplus** [comment]
Haha. Silly artman.

**Comment by lukesneeringer** [comment]
Closing this for now while I try to figure out what is needed.

**Pull request closed without merging**
