### PR TITLE
Fix #563 - Add breadcrumbs to the header.

### LINKED ISSUE #563: Add breadcrumbs when you're "zoomed in" to a specific method?
When we're zoomed in on a specific method (ie, https://googlecloudplatform.github.io/gcloud-node/#/docs/master/datastore/transaction?method=allocateIds)

We lose track of which module and class we're looking at (the sidebar is there, sure, but it's not really obvious).

I'm thinking it might be worthwhile to add headings, ie, for this example:

- h1: Datastore
- h2: Transaction
- h3: allocateIds

Thoughts?

### PR DESCRIPTION
**Pull request by jgeewax**
OK, new attempt here... Some issues with capitalization in this attempt (Bigquery instead of BigQuery, and likewise with PubSub vs Pubsub).

But... doesn't suffer from the same concerns as before with ACLs and whatnot...  Thoughts?

### CODE REVIEW

**Comment by ryanseys** [comment]
@stephenplusplus any idea how to get the module title with correct capitalization in this scope? Something like `$scope.moduleProper` would be nice here. I tried to tackle it for a bit but couldn't wrangle any sense out of it. Seems $scope.links contains objects that have the sidebar links which might be massage-able to get the current active module, however I'm sure there's a more efficient way of doing this.

**Comment by stephenplusplus** [comment]
https://github.com/stephenplusplus/gcloud-node/commit/5d9c4387394b4d601b87c1960a092d3bfeeb65b4 !

**Comment by ryanseys** [comment]
:+1: Can you put this in a new PR? This PR will close when the commit here is merged in yours.

**Comment by jgeewax** [comment]
Is that @ me or @stephenplusplus  ?

**Comment by ryanseys** [comment]
@stephenplusplus

**Pull request closed without merging**
