### PR TITLE
storage: run validation on raw response stream

### LINKED ISSUE #654: The downloaded data did not match the data from the server
Hey,
Any files that I get from the bucket "pubsite_prod_rev_", gets error code: CONTENT_DOWNLOAD_MISMATCH.

``` javascript
bucket.file("reviews/reviews_com.sample.android_201409.csv").download({
  destination: './reviews.cvs'
},
function(err, content){
  console.log(err.code);//CONTENT_DOWNLOAD_MISMATCH
});

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #654

**Previously**

If a file was uploaded with gzip content encoding, we were computing the hash of the _decoded_ file.

**Now**

We deliver the decoded file to the user, but compute the hash based on the raw, encoded file contents.

@beshkenadze - it would be awesome if you could try this out to see if the issue you were having is resolved.

### CODE REVIEW

**Comment by beshkenadze** [comment]
If not authorized request (403 error), then there is a exception. ;)

```bash
/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/lib/storage/file.js:552
        res.headers['x-goog-hash'].split(',').forEach(function(hash) {
                                  ^
TypeError: Cannot read property 'split' of undefined
    at DestroyableTransform.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/lib/storage/file.js:552:35)
    at DestroyableTransform.emit (events.js:107:17)
    at DestroyableTransform.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/index.js:31:26)
    at DestroyableTransform.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/node_modules/on-everything/index.js:12:17)
    at DestroyableTransform.obj.(anonymous function) [as emit] (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/node_modules/stubs/index.js:28:10)
    at StreamCache.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/index.js:31:26)
    at StreamCache.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/node_modules/on-everything/index.js:12:17)
    at StreamCache.obj.(anonymous function) [as emit] (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/node_modules/stubs/index.js:28:10)
    at Request.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/index.js:31:26)
    at Request.<anonymous> (/Users/akira/Projects/My/ReviewHub/src/node_modules/gcloud/node_modules/stream-forward/node_modules/on-everything/index.js:12:17)
```

**Comment by beshkenadze** [comment]
Otherwise, everything works! Excellent!

**Comment by stephenplusplus** [comment]
Thanks for testing, and great catch! I'm going to merge this and send a separate PR for the issue you found, as it spawned quite a few changes. (Hope you don't mind if I ping you again once that PR is in :))

**Comment by beshkenadze** [comment]
@stephenplusplus NP.

**Pull request merged**
