### PR TITLE
Only test 0.12.0

### PR DESCRIPTION
**Pull request by ryanseys**
Remove 0.10.0 and iojs testing from travis in hopes that we no longer have any issues with our regression tests so we can release!

### CODE REVIEW

**Comment by stephenplusplus** [comment]
This is the start of something amazing.

**Comment by stephenplusplus** [comment]
Or not: https://travis-ci.org/GoogleCloudPlatform/gcloud-node/#L1863
This error looks legit though.

**Comment by ryanseys** [comment]
Hmm... I couldn't reproduce on my local machine. Looks like more race conditions.

**Comment by ryanseys** [comment]
Created #440 in hopes to kill this issue.

**Pull request merged**
