### PR TITLE
docs: Remove region tags

### PR DESCRIPTION
**Pull request by camiekim**
Per b/296916003

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/{{metadata['repo']['name']}}/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by ddelgrosso1** [comment]
Hi @camiekim per the buganizer issue you linked should these be replaced with `workflows_client_library` as opposed to just removing them?

**Comment by camiekim** [comment]
Hi @ddelgrosso1, there is already an existing Node.js sample with the correct region tag (now) that is being used here: https://cloud.google.com/workflows/docs/samples/workflows-client-library?hl=en#workflows_client_library-nodejs_javascript

Thanks for checking though!

**Pull request merged**
