### PR TITLE
bigquery: remove automatic `insertId` generation & allow specifying raw format

### PR DESCRIPTION
**Pull request by stephenplusplus**
Closes #1066
### Breaking change included!

`insertId` is no longer defaulted to a value.

@vladmiller - Please take a look. I just wanted to change a few things (mostly style things) and also remove the default `insertId` generation. The CLA bot will say something about confirming you are the original author of this code. If you're okay with it, just leave a note that it's okay.

### CODE REVIEW

**Comment by vladmiller** [comment]
@stephenplusplus I think that we have to leave autogenerated insertID untouched s.t. old apps won't break.

**Comment by vladmiller** [comment]
Okay Google, contribute my commits.

**Comment by vladmiller** [comment]
Okay Google, I agree to contribute my commits.

**Comment by vladmiller** [comment]
Google set cla yes

**Comment by stephenplusplus** [comment]
We will just bump the minor version to follow semver rules for the breaking change (pre-1.0, a minor bump is equivalent to a post-1.0 major bump).

**Comment by stephenplusplus** [comment]
Thanks @vladmiller!

**Comment by vladmiller** [comment]
@stephenplusplus any estimate on when package becomes available in npm?

**Comment by stephenplusplus** [comment]
We're due for a release soon. Maybe I can get one out this week. In the meantime, you can use master:

```sh
$ npm install --save googlecloudplatform/gcloud-node
```

**Comment by vladmiller** [comment]
@stephenplusplus Thank you!

**Comment by vladmiller** [comment]
@stephenplusplus do you know when this PR will be merged?

**Comment by stephenplusplus** [comment]
Just needs a review from @callmehiphop.

This should work if you want to install from my branch for now:
```sh
$ npm install --save stephenplusplus/gcloud-node#vlad--patch-1
```

**Comment by callmehiphop** [comment]
@stephenplusplus Looks good to me!

**Comment by jgeewax** [comment]
@stephenplusplus I'm confused by this one. Why can't we allow control of the insert ID via overriding without keeping the auto-generation?

The request in #1066 was about being able to manually specify an insert ID, so adding the `raw` thing works, but taking out the other part kind of screws over the people who don't necessarily care about what value the ID is so long as it is unique (effectively saying "if an API request is one I've already sent, treat it as a duplicate")

The request in #1041 is about adding multiple of the same rows in parallel (aka, same timestamp, same data), so I can see how a hash wouldn't make sense there.

What we're trying to control for is:

- Insert rows `r`
- Request times out (maybe network cable was yanked, maybe GCP had an error)
- It's impossible to know for sure whether this batch of rows was added
- Retry inserting rows `r`

I'd argue that this is *not* for de-duping your data, and it is *not* for recovering after a client-side failure. If you want uniqueness or transactions like that, you should use a different storage system or de-duplicate, save to GCS, and bulk load the data.

Can we re-open the discussion about using a UUID-1 (or similar) to generate insert ID values when none are provided (and which are only used when we automatically retry a failed request) ?

**Comment by stephenplusplus** [comment]
Sure, let's move the convo back to the now re-opened #1041.

**Pull request merged**
