### PR TITLE
fix spelling mistake on "Bigquery"

### PR DESCRIPTION
**Pull request by polleyg**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/{{metadata['repo']['name']}}/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@bcoe can we disable these CI steps from this repo?

**Comment by bcoe** [comment]
@JustinBeckwith @stephenplusplus @polleyg this data is also generated automatically from templates, the sample just needs something like this added:

```js
// sample-metadata:
//   name: BigQuery
//   description: description of the sample
//   usage: node quickstart
```

**Comment by polleyg** [comment]
Ahh, sorry, my bad. Didn't know it was auto generated from templates. Looks like it's already been fixed in [PR #604](https://github.com/googleapis/nodejs-bigquery/pull/604) for the actual BQ repo.

**Comment by bcoe** [comment]
@polleyg nothing to be sorry for, thanks for reporting this.

**Comment by bcoe** [comment]
@stephenplusplus we should update `synth.py` on this repo to make it automatically generate the README.

**Pull request closed without merging**
