### PR TITLE
Allow NULL to be used as a property value

### PR DESCRIPTION
**Pull request by krisnye**
Fix for bug #1081

### CODE REVIEW

**Comment by krisnye** [comment]
I signed it!

**Comment by jgeewax** [comment]
@stephenplusplus : Would this be better as a separate if-statement line for nulls?

**Comment by stephenplusplus** [comment]
This doesn't actually work. The problem isn't with saving null data, but detecting a null value when it's returned from the API. We talked about this in #1022, and the easiest thing to do is wait for native support for a null value in the next version of Datastore, v1beta3... which hopefully is coming soon!

**Comment by krisnye** [comment]
Yes, reading the value back is a separate issue though.  At least being able to put a null value into the datastore can be supported immediately.

I, for one have no problem reading back the values, because I use a separate field which stores the entire JSON object I am interested in.  Other people could do a work-around if they know the intended type of the field.  There really is no work-around possible for not being able to put null into the datastore.

**Comment by stephenplusplus** [comment]
Since v1beta3 is around the corner, waiting for native support without side effects seems like the best solution to me. Supporting setting but not getting feels irresponsible for our library. However, feel free to share your examples in #1022, which will involve people who have already considered this problem. Maybe with all of our heads combined, we can find a solid way to support this now.

**Comment by krisnye** [comment]
Ok.  How soon is v1beta3 coming?

**Pull request closed without merging**
