### PR TITLE
docs - follow a version throughout the site

### LINKED ISSUE #548: Left navigation keeps bringing back to the master version
To reproduce:

1. Go to the docs: http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.14.0
1. Make note that you're looking at version 0.14.0
1. Click anything in the top section in the left nav bar (ie, PubSub)
1. Make note that you're now in the master branch version of the docs... (at least according to the URL)

Any ideas how we can avoid dropping into the master version?

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #548 

Preview: https://stephenplusplus.github.io/gcloud-node

### CODE REVIEW

**Comment by stephenplusplus** [comment]
I guess it's kind of hard to test on my branch, since I only host `master` - I'll push up the other versions from master, one sec.

**Comment by stephenplusplus** [comment]
Ok, ready to go. The "Read the docs" link will start at the latest version. If a user later changes the version, until they refresh, that version is honored throughout the site.

**Comment by ryanseys** [comment]
I wish I knew this code more to make a more informed code review. The demo looks like it fixes the issue though so merging. Code doesn't look too insane :)

**Comment by stephenplusplus** [comment]
As long as it looks a *little* insane :)

**Pull request merged**
