### PR TITLE
Add support for Cloud Functions

### PR DESCRIPTION
**Pull request by jmdobry**
- [x] - GAPIC code
- [x] - Implementation
  - [x] - Functions#cloudfunction
  - [x] - Functions#createFunction
  - [x] - Functions#getFunctions
  - [x] - Functions#getFunctionsStream
  - [x] - Functions#operation
  - [x] - CloudFunction#call
  - [x] - CloudFunction#create
  - [x] - CloudFunction#delete
  - [x] - CloudFunction#exists
  - [x] - CloudFunction#get
  - [x] - CloudFunction#setMetadata
- [x] - unit tests
- [x] - system tests
- [ ] - docs

### CODE REVIEW

**Comment by jmdobry** [comment]
@stephenplusplus @callmehiphop 

The Cloud Functions API `ListFunctions` method doesn't support pagination yet. I attempted to use the paginator for the `getFunctions` method, but limiting doesn't appear work. Here's [the skipped test](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1688/files?diff=unified#diff-7d7afb526358698f6ceb0a51994a4d52R182).

The PR is done (except for docs), barring any requested changes during review.

I experimentally implemented this PR using some ES2015 features (see #1855), and set the `engines` field in `package.json` to `"node": ">=4.3.2"` (it's the oldest 4.x version shown at [node.green](http://node.green/). I imagine the `@google-cloud/functions` package will be "alpha" for a while, then "beta", and by the time it's GA google-cloud-node will have dropped support for Node.js 0.12, so perhaps it can be a pilot for #1855.

**Comment by ofrobots** [comment]
@jmdobry not sure what view you're seeing, I do see more recent versions of Node.js 4.x on node.green (not that there is a difference in the list of supported language features that I am aware of between 4.3.x and 4.7.x)

**Comment by jmdobry** [comment]
I see the more recent 4.x versions too, but I thought it was prudent to stay compatible with older 4.x versions.

**Comment by jmdobry** [comment]
Instead of dropping support for 0.10 and 0.12 straight away in google-auth-library-nodejs, perhaps a better experiment would be to drop support for 0.10 and 0.12 in a brand new package, such as this one.

**Comment by stephenplusplus** [comment]
What's the plan / status of this?

**Comment by jmdobry** [comment]
Good question. cc @omaray 

## Option 1

Continue forward with this PR. There have been many changes to the google-cloud-node common libraries since I submitted this, so it's needs some work to get up-to-date. When I left off the PR was ready for review.

## Option 2

Expose the Gapic code to the user and delete the majority of my handwritten code, keeping only the helper function that zips and uploads a directory to Google Cloud Storage in preparation for creating/deploying a new Cloud Function (because it's a beast, and I'd hate to have to make users do all that themselves).

**Comment by lukesneeringer** [comment]
> Instead of dropping support for 0.10 and 0.12 straight away in google-auth-library-nodejs, perhaps a better experiment would be to drop support for 0.10 and 0.12 in a brand new package, such as this one.
 :+1: 1  

Worth noting: This has been adjudicated already. 0.12 support is gone.

**Comment by lukesneeringer** [comment]
> ### Option 1
>
> Continue forward with this PR. There have been many changes to the google-cloud-node common libraries since I submitted this, so it's needs some work to get up-to-date. When I left off the PR was ready for review.
>
> ### Option 2
>
> Expose the Gapic code to the user and delete the majority of my handwritten code, keeping only the helper function that zips and uploads a directory to Google Cloud Storage in preparation for creating/deploying a new Cloud Function (because it's a beast, and I'd hate to have to make users do all that themselves).

Our team is working on the concept of a "partial GAPIC", which is basically option 2. We should almost certainly do that. I should have a design doc soon and this could be a useful proof case for it.

**Pull request closed without merging**
