### PR TITLE
Fixes/docs v0.27.0 datastore dataset

### LINKED ISSUE #1074: duplicated information in runQuery docs
https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/datastore/dataset?method=runQuery

the "Parameters" table seems to have dup'd entries for the callback arguments... err, entities, nextQuery, apiResponse, err, entities, nextQuery, apiResponse.

there are slightly different descriptions, so it may have been that the older descriptions did not get deleted.

### PR DESCRIPTION
**Pull request by hrovira**
fixes #1074

### CODE REVIEW

**Comment by hrovira** [comment]
I signed the CLA

**Comment by stephenplusplus** [comment]
Thanks! Can you rebase against master and squash the commits?

**Comment by hrovira** [comment]
I was changing my author credentials for my commits (to satisfy CLA), and I made a mistake... working to fix now

**Comment by hrovira** [comment]
I will start over, for some reason github is not revert the last commits.

**Pull request closed without merging**
