### PR TITLE
Allow a base header for setEncryptionKey.

### LINKED ISSUE #2322: Storage - file.js. Any way to set Source Encryption Key?
Hi,
In File.js of the Storage package, the function setEncryptionKey() helps set the "x-goog-encryption-key" header. Is there a function to set the "x-goog-copy-source-encryption-key header"? Can a function be added for this please?

### PR DESCRIPTION
**Pull request by lukesneeringer**
@subra-vr Let me know if this gives you what you need.

Fixes #2322.

### CODE REVIEW

**Comment by subra-vr** [comment]
@lukesneeringer Thanks, this will work.

**Comment by stephenplusplus** [comment]
The `encryptionKey` option is accepted in a couple other places:

- The `File` constructor: https://github.com/lukesneeringer/google-cloud-node/blob/185bd501ecfd9b6bbf398c8251ca6852a6f85ab6/packages/storage/src/file.js#L83
- `bucket.file`: https://github.com/lukesneeringer/google-cloud-node/blob/185bd501ecfd9b6bbf398c8251ca6852a6f85ab6/packages/storage/src/bucket.js#L638 (note: there is apparently a typo in these docs-- the property name is not `key`)
- `bucket.upload`: https://github.com/lukesneeringer/google-cloud-node/blob/185bd501ecfd9b6bbf398c8251ca6852a6f85ab6/packages/storage/src/bucket.js#L1059

 Should we accept a `sourceEncryptionKey` option where these are as well?

**Comment by subra-vr** [comment]
@stephenplusplus I guess your query was targeted at @lukesneeringer as he requested the review? But in the interest of moving things along so I can get my code finalised, here goes. 
My original request was specifically for x-goog-copy-source-encryption-* headers which are applicable for rewrite operations. On the other hand, the above four finally end up being consumed in File object constructors, and something generic like options.baseHeader can be confusing there. So my opinion would be that options.baseHeader is enough just in the setEncryptionKey function. Over to @lukesneeringer. Thanks.

**Comment by subra-vr** [comment]
Hi @lukesneeringer @stephenplusplus , this is the first time I have raised an issue on a forum like this, so please bear with me if I ask the obvious. Any help on how and when this will get into the master branch?

**Comment by conundrum888** [comment]
@lukesneeringer Any chance this will be merged soon? Thanks.

**Comment by conundrum888** [comment]
Hi, my project really needs a way for the SDK to set source encryption key. Is the coverage check the reason this pull request is not merged?

**Pull request closed without merging**
