### PR TITLE
Append newline to end of extensionHeaders if necessary

### LINKED ISSUE #1316: storage/file#getSignedUrl: It shouldn't be necessary to add newline to end of extensionHeaders
The way storage/file#getSignedUrl computes the signature, it is necessary for the API client to end `extensionHeaders` with a newline, otherwise it won't correspond to the server's calculated signature. This should be handled automatically by gcloud-node.

### PR DESCRIPTION
**Pull request by aknuds1**
Fixes #1316.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thank you for this! What do you think about accepting an object for headers, e.g.

```js
file.getSignedUrl({
  extensionHeaders: {
    'x-goog-acl': 'public-read',
    'x-goog-meta-foo': 'bar'
  },
  // ...

File.prototype.getSignedUrl = function(options, callback) {
  ...

  var extensionHeadersString;

  if (options.extensionHeaders) {
    for (var headerName in options.extensionHeaders) {
      extensionHeadersString += format('{name}:{value}\n', {
        name: headerName,
        value: options.extensionHeaders[headerName]
      });
    }
  }

  ...
};
```

**Comment by aknuds1** [comment]
@stephenplusplus I also thought that an object would be better, but I thought about maintaining backwards compatibility and that it would be easier to fix the existing interface (extension headers represented by a string) if it's supposed to be supported in the future.

**Comment by stephenplusplus** [comment]
Thank you for thinking about the backwards compatibility issue, but it's okay to break it if we've discovered an easier API. We will just bump the minor to follow along with semver.

**Comment by aknuds1** [comment]
Do you want me to update the PR to represent extension headers as an object then?

**Comment by stephenplusplus** [comment]
If you're up for it, that would be great 👍

**Comment by aknuds1** [comment]
Will do then.

**Comment by aknuds1** [comment]
@stephenplusplus Done!

**Comment by stephenplusplus** [comment]
Merged in via https://github.com/GoogleCloudPlatform/gcloud-node/commit/17e510b32b0b2dfb1901c5d4b918df10daf36cc9. Thanks again @aknuds1!

**Pull request closed without merging**
