### PR TITLE
Update ruby SVG

### PR DESCRIPTION
**Pull request by blowmage**
Update the ruby SVG image. The current SVG is for rails, not ruby.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thanks! Which one #662 or this one?

**Comment by blowmage** [comment]
Both, I suppose. :)

**Comment by stephenplusplus** [comment]
Oh sorry, I realize now they are both the same file on different branches! gh-pages is built from our `docs` directory, so after merging that one, it should get copied over into gh-pages automatically. Thanks again!

**Comment by blowmage** [comment]
Yeah, I wasn't sure if it was replaced or not. I figured it would be easier to give you both and let you sort it out. Thanks!

**Pull request closed without merging**
