### PR TITLE
add maxInProgress option

### PR DESCRIPTION
**Pull request by stephenplusplus**
Continuing from #649

To Dos:
- [x] Tests
- [x] See what @callmehiphop has to say.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@leibale - as @googlebot says, please confirm you're okay with my incorporation of your work here :)

Also, please take a look when you can to make sure this works for you.

**Comment by leibale** [comment]
how confirm that? i already signed on CLA

**Comment by ryanseys** [comment]
There's no formal way of telling the bot we are ok with it, it's not a very smart bot. :) Just confirm with us that you're cool with these changes.

**Comment by jgeewax** [comment]
I just double checked -- leibale signed the CLA.

**Comment by leibale** [comment]
@stephenplusplus my code working like a charm :wink:.
my worker (in production) working with my fork repository few days.

**Comment by stephenplusplus** [comment]
@leibale great :) I was hoping you could test this branch out as well, as I had to make some changes to your original work.

**Comment by leibale** [comment]
what about that?

**Comment by stephenplusplus** [comment]
The code in this PR is different than what you originally sent us. Did you try out the code from this PR?

**Comment by leibale** [comment]
in "stephenplusplus/gcloud-node#spp--pubsub-add-maxInProgress" branch no option to mark message as done without ack, i cant test..

**Comment by stephenplusplus** [comment]
Can you explain that with some example code?

**Comment by leibale** [comment]
```javascript
subscription.on('message', function (message) {
  request.get(message.data.url, function (err) {
    if (err) { // return the message to the queue
      return subscription.done(); // inProgress--
    }
    
    subscription.ack(message.ackId);
  });
});
```

**Comment by stephenplusplus** [comment]
Okay, I think I misunderstood the idea originally, then. I think what you want is basically to be able to pause and resume the pulling? Would just adding `.pause()` and `.resume()` methods work for your use case?

**Comment by leibale** [comment]
no.. if i try to process message and i got error i need to down the inProgress without ack the message.

my english so bad :(

**Comment by leibale** [comment]
and..?

**Comment by stephenplusplus** [comment]
Sorry @leibale, holiday weekend and #701 blew up my mind today :bomb: :man: :cloud:. I'll be revisiting this soon, and don't worry, the misunderstandings are my fault only.

**Comment by leibale** [comment]
i want to remove my fork and go back to master branch- time estimation for this enhancement?

**Comment by stephenplusplus** [comment]
Sorry for the delays. I hopefully addressed this now with a new method, `skip`. So, from your previous example, this would look like:

```js
subscription.on('message', function (message) {
  request.get(message.data.url, function (err) {
    if (err) {
      return message.skip();
    }

    subscription.ack(message.ackId); 
  });
});
```

Both `skip` and `ack` will `--` the counter. Please try it out!

**Comment by leibale** [comment]
now it's looks good- i try it tomorrow

**Comment by leibale** [comment]
`ack` doesn't `--` the counter (only skip)

**Comment by stephenplusplus** [comment]
Woops, good catch. Thanks!

**Comment by leibale** [comment]
@stephenplusplus pls let me know when you fix this

**Comment by leibale** [comment]
You will working on this in the next hour?

**Comment by stephenplusplus** [comment]
@leibale :+1:

**Comment by leibale** [comment]
@stephenplusplus you need to delete the ackId(s) from inProgressAckIds

**Comment by stephenplusplus** [comment]
That was embarrassing.

**Comment by leibale** [comment]
@stephenplusplus :+1:
now i just want this on the master and.. :P

**Comment by stephenplusplus** [comment]
Haha, me too! As long as you give me longer than an hour :) I hope to get a lot of the outstanding PRs merged by the end of the week, and if that goes well, I'll speed this one up.

**Comment by leibale** [comment]
ok. thanks alot for everything. :)

**Comment by leibale** [comment]
another mistake- you need to do the ``--`` only if ``!err``

**Comment by stephenplusplus** [comment]
Thanks! Fixed.

**Comment by stephenplusplus** [comment]
@callmehiphop PTAL.

**Comment by callmehiphop** [comment]
LGTM :+1:

**Comment by stephenplusplus** [comment]
Thanks for the review and thanks for the idea @leibale!

**Pull request merged**
