### PR TITLE
integrate support for GAE dev

### PR DESCRIPTION
**Pull request by stephenplusplus**
## Do not merge

RE: #104
Blocked by: #233
Sucessor to: #154 

This isn't immediately useful, but is a modernized adaptation of #154.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
To do: use the environment's project ID - https://github.com/GoogleCloudPlatform/gcloud-node/issues/365#issuecomment-72556291

**Comment by jgeewax** [comment]
(Added label based on the heading...)

**Comment by jgeewax** [comment]
Just out of curiosity -- If I'm in App Engine, and want to talk to *another* project's datastore, and I *do* have the keyfile, can I still do that?

To put it another way, in App Engine, if I provide nothing to the code and just "hope that it figures it out", I'd want it to write to my App Engine app's datastore. I still want the ability to provide a specific set of credentials and a datastore/dataset ID (right now, this is equivalent to a project ID) and have my code talk outside my current app's dataset. Is that doable?

**Comment by ryanseys** [comment]
Just quickly looking at the PR here, it doesn't look like it gives us that option. If it detects that we are on GAE, it will automatically use those credentials to authorize the calls. It should definitely provide the option, i.e. if we provide configuration options, it will use those ALWAYS before defaulting to attempting GAE detection.

**Comment by jgeewax** [comment]
:+1: to @ryanseys : I think we really need to make sure that code does the same thing across platforms.

If I manually configure my connection with a specific key, it should do the same thing on GCE as it does on GAE. It sounds like that isn't the case here.

@stephenplusplus : Can you take a look?

**Comment by stephenplusplus** [comment]
If a user provides configuration details, regardless of environment, that should definitely be honored (good catch!). It was overlooked in my original implementation, but I updated to support custom connection configuration never being precedented by magic.

**Comment by stephenplusplus** [comment]
#458 will squash this.

**Comment by stephenplusplus** [comment]
@coveralls you're so weird.

**Pull request closed without merging**
