### PR TITLE
Clarify bucket metadata example

### LINKED ISSUE #370: Docstring for bucket.setMetadata has invalid argument
From [the code][1]:

```javascript
bucket.setMetadata({
  contentType: 'application/x-font-ttf',
  metadata: {
    my: 'custom',
    properties: 'go here'
  }
}, function(err, metadata) {});
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-node/blob/fcc6123ddb0678f29d9ccd606e81318f988b4fa8/lib/storage/bucket.js#L308

### PR DESCRIPTION
**Pull request by ryanseys**
Fixes #370

### CODE REVIEW

**Comment by dhermes** [comment]
Shouldn't the key just be `metadata`?

**Comment by ryanseys** [comment]
According to [this](https://cloud.google.com/storage/docs/json_api/v1/buckets/patch) no such key exists.

**Comment by stephenplusplus** [comment]
LGTM - this is the way our regression test does it: https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/regression/storage.js#L289

**Comment by dhermes** [comment]
Sorry I confused myself (was looking on my phone) both about the value being passed and the relevant noun (I thought we were talking about objects, not buckets).

:+1:

**Pull request merged**
