### PR TITLE
Add system-test for GAPIC files for logging API.

### PR DESCRIPTION
**Pull request by jmuk**
This is hand-written for now. Eventually, we will replace this
by automatically generated ones.

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Some linting errors:

```
> jshint scripts/ packages/ system-test/ test/ && jscs packages/ system-test/ test/

packages/logging/system-test/v2.js: line 62, col 11, 'start' is defined but never used.
packages/logging/system-test/v2.js: line 113, col 37, Strings must use singlequote.
packages/logging/system-test/v2.js: line 124, col 7, Missing semicolon.
packages/logging/system-test/v2.js: line 186, col 78, 'resp' is defined but never used.
``

**Comment by jmuk** [comment]
Fixed lint errors.

**Comment by stephenplusplus** [comment]
@jmuk is it possible these tests are better suited for the gax repo? As I understand this, these tests are certifying that the gax library works. But, we should always be able to assume it works, because there wouldn't have been a gax release unless tests like these passed. Does this make sense?

**Comment by jmuk** [comment]
This is a bit different from gax-nodejs repo because it tests API-agnostic logic, while our code generator tests the generated files, character-by-character. This PR verifies the behaviors of generated files -- i.e. whether it's syntactically correct or not, or whether it can issue API calls correctly or not.

However we have another repository `api-client-staging` to store the autogen results (and actually I put the baseline of this PR already there, as https://github.com/googleapis/api-client-staging/tree/master/test/nodejs/logging). If that's good enough, I'll keep using that repository for those tests for autogen results.

Feel free to close this if that sounds good.

**Comment by stephenplusplus** [comment]
Thanks, `api-client-staging` sounds like the perfect place 👍

**Pull request closed without merging**
