### PR TITLE
Subscription#new add option maxInProgress

### PR DESCRIPTION
**Pull request by leibale**
Subscription#new add option maxInProgress (to make sure the application working on {Number} messages in parallel)

### CODE REVIEW

**Comment by leibale** [comment]
i fixed the "cla/google — Need a CLA for one or more commit authors" issue,
about the "The Travis CI build failed"- i don't know what is it..

**Comment by leibale** [comment]
why the CLA issue not resolve?

**Comment by jgeewax** [comment]
Looks like the commits are authored by `dov_eidelman`... If you authored the commits, you need to set the e-mail address to be your GitHub e-mail address. See http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit for help on amending previous commits to update the true author.

**Comment by leibale** [comment]
now the commit are authored by "leibale" but the pull request still with "cla:no" label

**Comment by stephenplusplus** [comment]
Thanks @leibale! I'm going to implement this functionality in a new PR to address some styling issues. I'll ping you over when it's ready to take a look, and hopefully you can check it out and make sure it still works for you.

**Comment by leibale** [comment]
ok :)

**Comment by stephenplusplus** [comment]
Closed in favor of #650

**Pull request closed without merging**
