### PR TITLE
docs: de-emphasize downloading service account keys

### PR DESCRIPTION
**Pull request by sethvargo**
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by sofisl** [comment]
@sethvargo, this seems like a pretty substantial change in direction. Is there guidance coming from elsewhere to make this change? Otherwise, perhaps we might want to talk it over with other Node owners (apologies if I missed a convo/message about this).

**Comment by sethvargo** [comment]
@sofisl in general, downloading service account JSON keys should be the **last** choice. Check the yoshi chat.

**Comment by JustinBeckwith** [comment]
We did have a discussion on this today in the team chat, and decided we needed to address this in a more holistic way.  This may turn out to be the answer (I hope it is!) but we have to address some of the key issues first, and then make sure we're tracking all the places this would have to be changed.  This is but one of 100 places we would need to update.

**Comment by tmatsuo** [comment]
Let's close this for now.
(We can always reopen)

**Pull request closed without merging**
