### PR TITLE
Update to CRC module and fix self register

### PR DESCRIPTION
**Pull request by ryanseys**
Inherits from #488

### CODE REVIEW

**Comment by ryanseys** [comment]
Fear not, dear @googlebot.

**Comment by ryanseys** [comment]
@anandsuresh Will wait for Travis to confirm this actually works, then will merge and close other PR.

**Comment by anandsuresh** [comment]
Aaah! I see now that Mockery needed to be told about the new module in order to get that to work. My bad. I didn't realize that was a requirement.

Having said that, a more descriptive error message might have made this easier. :tired_face:

**Comment by ryanseys** [comment]
Yeah something like that. I don't actually know much about the register and deregister system in node regarding requiring modules and caches and all that jazz, but this seemed to fix it on my machine so I'm running with it. I believe it's an issue because it's required both inside the test file and the file.js. That combined with the fact that it's a native module on node 0.12.0 is a recipe for disaster.

**Comment by stephenplusplus** [comment]
It passed! It passed!

**Comment by ryanseys** [comment]
:D

**Comment by anandsuresh** [comment]
Yaay!! Finally done! :)

**Pull request merged**
