### PR TITLE
Add Google Drive scope to BigQuery

### PR DESCRIPTION
**Pull request by abetomo**
You can set up Google spreadsheets for BigQuery data sources.
However, executing the query resulted in an authorization error.

The following error occurred.
```
  code: 403,
  errors: 
   [ { domain: 'global',
       reason: 'accessDenied',
       message: 'Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern.',
       locationType: 'other',
       location: '/gdrive/id/****' } ],
  response: undefined,
  message: 'Access Denied: BigQuery BigQuery: Permission denied while globbing file pattern.' }
```

### CODE REVIEW

**Comment by abetomo** [comment]
I signed it!

**Comment by stephenplusplus** [comment]
Thanks for this PR! @lukesneeringer what do you think about this?

**Comment by stephenplusplus** [comment]
@swcloud for thoughts as well.

**Comment by abetomo** [comment]
@stephenplusplus @lukesneeringer @swcloud 
How about this PR?
If there is a problem I will fix it so please point out.

**Comment by fujio0000** [comment]
@lukesneeringer
I am having the same problem.
When is the merge around?

**Comment by abetomo** [comment]
@lukesneeringer @swcloud
Currently, it is used frequently with Google spreadsheet as a data source.
Thank you for your review.

**Comment by ifokeev** [comment]
The same issue here.
UP

**Comment by c0b** [comment]
is there a drive.read_only role? for the permission concern, I see bigquery can only read from drive but cannot / no need to write to gdrive?

**Comment by stephenplusplus** [comment]
The BigQuery code is now at https://github.com/googleapis/nodejs-bigquery. Thank you for this PR -- I'm not sure what the right thing to do is, so I can't merge or encourage you to resend the PR, since I'm not sure it will be merged there. Pinging @lukesneeringer again for input.

**Pull request closed without merging**
