### PR TITLE
Nodejs GAPIC: vision v1

### PR DESCRIPTION
**Pull request by lukesneeringer**
RE: #2225

This pull request was generated by artman. Please review it thoroughly before merging.

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Related to #2225, and is sufficient to drop that issue to "not P0".

**Comment by lukesneeringer** [comment]
@stephenplusplus After this is merged, can you cut a new patch release of Vision?

**Comment by stephenplusplus** [comment]
For sure.

**Comment by lukesneeringer** [comment]
@stephenplusplus  Merged. Please do the things.

**Pull request merged**
