### PR TITLE
Add errors system-test to system-test run

### PR DESCRIPTION
**Pull request by cristiancavalli**
TODOS:

- [x] Update `env.js` with new fields
- [x] Add relevant values to process for CI run for `env.js`
  - [x] Circle
  - [x] AppVeyor
- [x] Update errors system-test to use `env.js` file
- [x] Make sure error reporting is enabled on CI project

### CODE REVIEW

**Comment by cristiancavalli** [comment]
@stephenplusplus @callmehiphop  Is there anyway we could plant the newly added env values into the CI?

Currently the test wants two values:
- [ ] The project number which can be used interchanbly for the project id
- [ ] A valid API-key for the project [instructions for which can be found here](https://support.google.com/cloud/answer/6158862?hl=en)

**Comment by stephenplusplus** [comment]
I've added the number (1046198160504) and API key to Circle-- I don't have access to the settings on AppVeyor

@lukesneeringer -- can you add an env var to AppVeyor, `GCLOUD_TESTS_PROJECT_NUMBER` set to `1046198160504`? I believe `GCLOUD_TESTS_API_KEY` is set, but if not, let me know.

@cristiancavalli can you add these env vars to https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/.github/CONTRIBUTING.md and also make them optional-- i.e. the `describe` block will be skipped if the env vars aren't set, something like:

```js
var PROJECT_NUMBER = process.env.GCLOUD_TESTS_PROJECT_NUMBER;
var API_KEY = process.env.GCLOUD_TESTS_API_KEY;

var SHOULD_RUN = PROJECT_NUMBER && API_KEY;

(SHOULD_RUN ? describe : describe.skip)('error-reporting', function() {
  // ...
});
```

**Comment by cristiancavalli** [comment]
@lukesneeringer assigning you as well because of the necessary appveyor changes

**Comment by stephenplusplus** [comment]
Just an edit to CONTRIBUTING.md (https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/.github/CONTRIBUTING.md) to add the new ENV var in would be 👍

**Comment by cristiancavalli** [comment]
@lukesneeringer 
screen shot 2017-04-11 at 8 58 47 am

**Comment by ofrobots** [comment]
@lukesneeringer @stephenplusplus It would be good move forward on this and #2208 so that we can get the error-reporting module published in time for the upcoming beta.

**Comment by lukesneeringer** [comment]
Sorry.

I added the project number to AppVeyor. The key is not set, so you will need to send it to me privately to set.

**Comment by lukesneeringer** [comment]
Both environment variables are now set in AppVeyor.

**Comment by stephenplusplus** [comment]
Tested locally with the system test credentials and all went well. Thanks @cristiancavalli! I'll merge after the new info is in CONTRIBUTING.md.

**Comment by cristiancavalli** [comment]
@stephenplusplus Not sure why it's not showing up in the diff, if you pull from the branch it has the edit to contributing.md

screen shot 2017-04-13 at 1 18 38 pm

**Comment by stephenplusplus** [comment]
Could that be coming from #2208? I see the edit over in that PR.

**Comment by cristiancavalli** [comment]
Just pushed more changes to this branch on CONTRIBUTING, they don't seem to be propagating over..

**Comment by stephenplusplus** [comment]
My faith in any code I've ever reviewed is shaken!

**Comment by cristiancavalli** [comment]
So weird, let me try reopeneing it

**Comment by stephenplusplus** [comment]
GitHub has been known to be behind on things like emails and commit logs. Haven't seen this issue before. After some long-running things are done in my terminal, I'll clone and check it out. I noticed it's not on the branch either when browsing the tree on GH.

**Comment by stephenplusplus** [comment]
That file is not edited in my checked out branch either.

**Comment by cristiancavalli** [comment]
hey @stephenplusplus my bad -- had the a different source repo checked out. Value should be updated in CONTRBUTING -- please lmk if the copy should be worded differently

**Comment by stephenplusplus** [comment]
There it is! I simplified it a bunch just to be a little more future-proof (not listing the APIs that need them). Merge time!

**Pull request merged**
