### PR TITLE
return Total Rows

### PR DESCRIPTION
**Pull request by sunnychow**
return Total Rows
#427

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thank you for taking a crack at the issue! Can you explain what this PR is doing? I'm not sure I see how total rows is being returned, but I might be distracted by the formatting changes. Could you please keep with the style of the project (2 space indentation)?

Thanks!

**Comment by ryanseys** [comment]
Seems the tests are failing now, so those will need to be addressed in your PR. You can run the tests locally with `npm test`. Regarding the approach of this PR, we don't return the raw response object for any requests so I can't see us making an exception for this case, the object that returns rows will need to be adjusted to return the totalRows property as well. This would be a backward-incompatible change which sucks, but seems necessary. 

Aside: @stephenplusplus we have no clear way on how to handle these regressions caused by the addition of more attributes in the return body. We should likely discuss a best-practices approach to this because I anticipate it will happen a lot in the future and I'd prefer to not break everyone's code when it does happen and we need to change things.

**Comment by sunnychow** [comment]
I think the best practices approach to this is returns the response object. For example, in the line
https://github.com/sunnychow/gcloud-node/blob/26bca6bd7d7f909e6eeaf77cab938bf1c56a6910/lib/bigquery/index.js#L412
we should change it to
```
onComplete(null, rows, nextQuery, resp);
```
This is because google big query returns useful information in the resp. https://cloud.google.com/bigquery/docs/reference/v2/jobs/getQueryResults
For example, `kind`, `etag`, `totalRows`

**Comment by stephenplusplus** [comment]
This will be solved by #448, where we return the raw API response for all calls. Thanks for getting this started, @sunnychow!

**Comment by sunnychow** [comment]
thank you.

**Pull request closed without merging**
