### PR TITLE
core: use google-auto-auth

### LINKED ISSUE #822: Caching of auth client regressed by #705
I believe that PR #705 regressed the earlier fix to cache the auth client I contributed in #661. This means that a new cache client is created on each API request we make, adding an unnecessary performance overhead. Here's some Cloud Trace output I get:

image

Note the extra 141ms added to this request, and every other request.

The cause is that the function [`makeAuthorizedRequest`](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/common/util.js#L465) now passes a brand new object to `util.makeRequest` each time. We cache the authClient on that object, which is temporary and not available the next time through.

Would it be possible add a test for this to make sure this doesn't get regressed?

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #822 

This incorporates https://github.com/stephenplusplus/google-auto-auth into our library, replacing `google-auth-library` (kind of; it's wrapped by `google-auto-auth`).

// cc @ofrobots

### CODE REVIEW

**Comment by jgeewax** [comment]
/cc @anthmgoogle (working on the auth libraries)

@stephenplusplus : Any reason why we couldn't push the commits upstream into google-auth-library?

**Comment by stephenplusplus** [comment]
google-auth-library is much more complex and lacks documentation. google-auto-auth was just built to simplify it with a more conventional JS approach. I don't think this approach (high-level userland packages that wrap more low-level ones) is anything to worry about.

**Comment by jgeewax** [comment]
Cool - if it's something specific like this, maybe we can get it shoved under the google or GCP github organization...?

**Comment by stephenplusplus** [comment]
That's fine with me, though seeing two repos that handle authorization in Node under the same org might be a bit confusing to a user. I'm happy to transfer the ownership of the repo though if you don't think that's a concern.

**Comment by jgeewax** [comment]
Eh let's leave it alone for now, and keep it as an idea for discussion
later on...

**Comment by stephenplusplus** [comment]
SGTM :+1:

**Pull request merged**
