### PR TITLE
Fixed missing production dependency: methmeth

### PR DESCRIPTION
**Pull request by tehsenaus**
This is used in src/session-pool.js

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Amazing, thank you. I'm going to release separately due to the CLA thing, and release immediately. 

Just wondering, how did you run into this? It's actually been this way since the beginning-- `methmeth` must have been loading as an indirect dependency.

**Comment by stephenplusplus** [comment]
Fixed in 6d090ee800e004a07ed180df2eaa513bdd1db603 and released under `@google-cloud/spanner@0.4.1` -- thanks again!

**Comment by tehsenaus** [comment]
I think this was working before due to the shrinkwrap.json in the root project.

I had to install with --no-shrinkwrap due to being behind a corporate proxy (shrinkwrap forces it to go to public NPM and we have a private instance, but that's another issue), and then the issue manifested itself.

**Comment by stephenplusplus** [comment]
Ah, interesting. Thanks for the info. Can you try now to see if it's resolved? That would save us a release of `google-cloud` if it's not required.

**Comment by tehsenaus** [comment]
Yes ```google-cloud@0.51.1``` is pulling in the fixed version.

Thanks for the quick fix!

**Pull request closed without merging**
