### PR TITLE
Create a new issue template

### PR DESCRIPTION
**Pull request by stephenplusplus**
cc: @callmehiphop @jgeewax

### CODE REVIEW

**Comment by callmehiphop** [comment]
I really like the tone of the template, but I'm not so sure about the general format. I think I find the use of checkboxes a bit puzzling, especially where we're asking for technical details.

I was kind of expecting something closer to

```md
### OS

### Node version

### gcloud version

### Steps to reproduce
```

Although this isn't nearly as pretty and doesn't convey any sort of tone.

**Comment by jgeewax** [comment]
I kind of like the checkboxes... It means they can check off that they did those things... However it's not a checkbox until they create the issue , so that's... iffy. 

I think the `### OS` , etc is probably a bit too sparse. Any chance we can do something in the middle?

**Comment by stephenplusplus** [comment]
PTAL

**Comment by callmehiphop** [comment]
Looks great to me!

**Pull request merged**
