### PR TITLE
Logging: allow for camelcase resource labels

### LINKED ISSUE #2494: Logging resource labels use snake_case rather than camelCase
*Originally reported by @jwgoh in https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2484*

I tried specifying the monitored resource manually. The keys for labels seems to only take snake_case i.e. project_id and NOT camelCase projectId.

```
// Works
resource: {
  type: 'gce_instance',
  labels: {
    project_id: projectId,
    instance_id: instanceId,
    zone: zone,
  },
},

// Does not work. Nothing gets logged
resource: {
  type: 'gce_instance',
  labels: {
    projectId: projectId,
    instanceId: instanceId,
    zone: zone,
  },
},
```

I referred to the documentations [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/a64518e80742429dd3b4021a6f74c8235faa0375/packages/logging-winston/src/index.js#L82-L86) and [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/MonitoredResource) when specifying the key-value.

### PR DESCRIPTION
**Pull request by landrito**
Resolves #2494

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Awesome, thanks!

**Comment by ofrobots** [comment]
What is the semver-ness of this change?

**Comment by stephenplusplus** [comment]
- Users providing snake case before can continue to provide snake case
- Users providing camel case before would not see those properties saved
- Users providing camel case after will see those properties saved

If that's all true, I would see this as a fix. The only thing that will change unexpectedly for a user is that our advertised API will work as they thought it would (but didn't notice that it wasn't).

Did I miss anything? What do you think?

**Comment by ofrobots** [comment]
That reasoning is good :+1:, thank you!

However, why do we need to special case `resource.labels` for snake_casing? For example, the of the logging code base provides properties of the form `entryMetadata.httpRequest` and that works fine.

Does some layer (common? gax? grpc?) convert those keys to snake_case automatically, but somehow `resource.labels` were missed? Or is it this a problem in the logging service?

**Comment by landrito** [comment]
The resource labels are a predefined list with a specific casing structure that can be found here:
https://cloud.google.com/logging/docs/api/v2/resource-list

**Pull request merged**
