### PR TITLE
site: add external link - fixes #552

### LINKED ISSUE #552: Put a little external-link icon next to links that take you away from the docs?
Any objection to putting an external link icon (ie, http://fortawesome.github.io/Font-Awesome/icon/external-link/) next to links that take you out of the github.io page?

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #552 

Preview: https://stephenplusplus.github.io/gcloud-node/#/docs/master

### CODE REVIEW

**Comment by jgeewax** [comment]
That looks awesome. Nice!

**Comment by ryanseys** [comment]
Damn, that's neat. But it does look pretty cluttered. Can't we just set `target="_blank"` on all external links?

**Comment by stephenplusplus** [comment]
I think this is just to denote that they are external links. Any ideas on how to de-clutter?

**Comment by jgeewax** [comment]
Wait what exactly is cluttered? Are you saying the little external link icons are causing too much clutter? I'm seeing on average 1-2 per method, the occasional 3... I think it's useful to know when I'm leaving the docs...

**Comment by ryanseys** [comment]
I think I just needed a minute to warm up to it. I was probably looking at a particularly cluttered area. Sorry for the false alarm.

**Comment by jgeewax** [comment]
Cool - LGTM.

**Pull request merged**
