### PR TITLE
datastore | logging: promote to GA

### PR DESCRIPTION
**Pull request by stephenplusplus**
#### Blockers

- [ ] [automatic batching interface for cloud logging client](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1296)
- [x] [gRPC memory leak](https://github.com/grpc/grpc/issues/10445)

### CODE REVIEW

**Comment by lukesneeringer** [comment]
@ofrobots Is this good now that the memory leak is fixed?

**Comment by ofrobots** [comment]
sgtm from my side.

**Comment by lukesneeringer** [comment]
@stephenplusplus You have the go-ahead to do this tomorrow morning.

**Comment by stephenplusplus** [comment]
Just going over the issues left for Logging and Datastore. All but one issue will involve backwards-compatible fixes. The one I'm not sure of is a feature request for a batching interface in Logging: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1296

I think we should hold off on going GA for Logging until I have a better understanding of what's required for that issue. I've labeled it as <kbd>status: release blocking</kbd> for now.

**Comment by lukesneeringer** [comment]
Uggggh. This will become urgent extremely quickly, so let's discuss in our Monday meeting how to knock these out as quickly as possible.

**Comment by stephenplusplus** [comment]
I think we might be able to move forward with the release if @ofrobots finds an extra minute to let us know if it's not as serious as I'm making it out to be: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1296#issuecomment-293908332. If it's just a feature that won't affect backwards-compatibility (which I *think* it is), then we can get on with the release.

**Comment by ofrobots** [comment]
I will try to take a look tomorrow.

**Pull request merged**
