### PR TITLE
Implement Service & Service Object for PubSub

### PR DESCRIPTION
**Pull request by stephenplusplus**
For #904

This hooks Pub/Sub up with Service & ServiceObject.

### CODE REVIEW

**Comment by callmehiphop** [comment]
Instead of using a multiple inheritance lib, what are your feelings on just having `ServiceObject` extend `EventEmitter`? I realize that this will add event emitter methods to all service classes, however they'll be undocumented and won't really bring any overhead.

**Comment by stephenplusplus** [comment]
That sounds a little crazy. Why would we do that?

**Comment by callmehiphop** [comment]
Well if you just create a prototype chain, then you can have something inherit for multiple "classes". And it seems to me that the only reason we're even including a multiple inheritance lib is because on certain objects we want to use `EventEmitter` but we're already extending a `ServiceObject`.

**Comment by stephenplusplus** [comment]
That is why we're using it. But that's the only place we need it, so I
don't think it's more logical to make all classes event emitters.

**Comment by callmehiphop** [comment]
Well, that's not true - https://github.com/GoogleCloudPlatform/gcloud-node/pull/939 is also using it to extend both an event emitter and service object.

**Comment by stephenplusplus** [comment]
The point is not all. I don't think we want all of our classes to be event
emitters, just the ones that need it.

**Comment by callmehiphop** [comment]
Fair enough!

**Pull request merged**
