### PR TITLE
Incorrect missing project ID error URL

### PR DESCRIPTION
**Pull request by bamapookie**
The URL in the error message does not actually take you to the authentication documentation.  Fixed in the fork.

### CODE REVIEW

**Comment by bamapookie** [comment]
I signed it.

**Comment by stephenplusplus** [comment]
Thank you for finding this. This is kinda silly, but we have an 80 char rule, so if you don't mind, can you make these changes?

```diff
var extend = require('extend');
+ var format = require('string-format-obj');
var googleAuth = require('google-auto-auth');

...

var errorMessage = format([
  'Sorry, we cannot connect to Google Cloud Services without a project ID.',
  'You may specify one with an environment variable named "GCLOUD_PROJECT".',
  'See {baseUrl}/{path} for a detailed guide on creating an authenticated',
  'connection.'
].join(' '), {
  baseUrl: 'https://googlecloudplatform.github.io/gcloud-node/#',
  path: '/docs/guides/authentication'
});

var missingProjectIdError = new Error(errorMessage);
```

**Comment by bamapookie** [comment]
Thanks, @stephenplusplus.  I was wondering how I was going to make that URL fit. :)

**Comment by stephenplusplus** [comment]
Awesome, thanks :) And sorry again, but I forgot that we have [this test](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/test/common/util.js#L112) this is going to fail now. That will need the same update. I'm pretty confident that should be it!

**Comment by stephenplusplus** [comment]
Perfect, thank you very much! 💃

**Pull request merged**
