### PR TITLE
Storage is moving.

### PR DESCRIPTION
**Pull request by lukesneeringer**
Storage is moving! https://github.com/googleapis/nodejs-storage

### CODE REVIEW

**Comment by lukesneeringer** [comment]
I am sure there is _something_ else that needs to be done...

**Comment by stephenplusplus** [comment]
There are some storage references in these files (some, more than one): 

- https://github.com/GoogleCloudPlatform/google-cloud-node/blob/42eef91924d859ada7ffca2707d2e556eddd90bd/scripts/docs/config.js#L44
- https://github.com/GoogleCloudPlatform/google-cloud-node/blob/f53c6f6f94206d5b2d9e366215311ce65657a1a2/.github/CONTRIBUTING.md (`cd packages/storage`)

But I think that's it!

**Comment by stephenplusplus** [comment]
@callmehiphop -- CI errors: https://ci.appveyor.com/project/googleapis/google-cloud-node/build/1.0.1051/job/jl2mbw1evcspopdu -- we can ignore that, given the fact that we're flat out removing files from the repo, right?

**Comment by callmehiphop** [comment]
@stephenplusplus yeah I think so, I'm not sure deleting a package was ever anything we planned on, haha.

**Comment by stephenplusplus** [comment]
Let's see how the merge goes!

**Pull request merged**
