### PR TITLE
ci: set git user

### PR DESCRIPTION
**Pull request by stephenplusplus**
```
git add manifest.json json
git commit -m "Update docs for master [ci skip]"
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
```

https://travis-ci.org/GoogleCloudPlatform/google-cloud-node/jobs/163785024#L1085

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Windows probs:

```
exec: internal error
C:\projects\google-cloud-node\scripts\helpers.js:260
  if (response.code) {
              ^
TypeError: Cannot read property 'code' of null
```

**Comment by stephenplusplus** [comment]
I think I fixed it with my last commit.

**Comment by callmehiphop** [comment]
Dang, must be a quirk of the submodule..? So there's already a line that tries to set the user, can we just add the `--global` flag to that?

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/scripts/helpers.js#L318

**Comment by stephenplusplus** [comment]
Woops, didn't see that. Added the global flag there.

**Pull request merged**
