### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Awesome, thanks!

**Comment by stephenplusplus** [comment]
cc @googlebot

**Comment by stephenplusplus** [comment]
@kevinresol -- usually @googlebot checks if you've signed the Google CLA and tells you how to if you haven't already. I'll have to fill in for @googlebot, since he seems to have fallen asleep on the job.

If you haven't signed the CLA, the instructions on that here: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.36.0/guides/contributing). If you're cool with it, after you sign it, let me know.

Sorry for the unexpected CLA dance. 💃

**Comment by kevinresol** [comment]
@stephenplusplus Done

**Comment by stephenplusplus** [comment]
Thanks!

**Pull request merged**
