### PR TITLE
chore: license checking in posttest

### PR DESCRIPTION
**Pull request by jinwoo**
This can't be checked in until a license issue with
`@google-cloud/common-grpc` is fixed. It has a transitive dependency,
`jsonify`, which has "Public Domain" as its license. But Public Domain
is not a valid license for Google's open source projects.

Also the 'log-driver' package is whitelisted.

Additonal minor changes:
- add the `version` field: this is a required field
- fix the `private` field: this is a boolean field. "true" --> true.
- package-lock.json is committed.

### CODE REVIEW

**Comment by jinwoo** [comment]
The license checking fails due to `jsonify`. The issue is tracked by https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2786.

**Comment by jinwoo** [comment]
Huh? All CI tests passed, which is unexpected. They should've failed in the `posttest` phase.

Looking at the test setup, it looks like none of the tests are actually run. Test scripts just run lint and the build script. Is this intended?

**Comment by jinwoo** [comment]
@stephenplusplus Can you check the CI setup? None of the tests seem to run on CI.

**Comment by stephenplusplus** [comment]
Hey @jinwoo, we just branched common-grpc out into its own repo: https://github.com/googleapis/nodejs-common-grpc. Can you add the license checking changes there? I'm not sure what the fate of this repo will be, but that was the last bit of code we had here.

**Comment by jinwoo** [comment]
Got it. Branching out common-grpc seems like the way to go. Thanks.

**Pull request closed without merging**
