### PR TITLE
Add dummy js files for datastore gapic/proto documentation

### LINKED ISSUE #1492: Documenting Gapic/Proto (autogen files)
Opening an issue to track discussion on how we should go about documenting GAX from within our library.

### PR DESCRIPTION
**Pull request by swcloud**
Fixes #1492

This should help fix #1492

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Adding `do not merge` while I work on this and the docs parsing changes needed. I'll keep this PR updated with the progress.

**Comment by stephenplusplus** [comment]
@swcloud PTAL: https://stephenplusplus.github.io/gcloud-node/#/docs/datastore/master/datastore/

**Comment by swcloud** [comment]
@stephenplusplus That's certainly a good progress!

A few comments here:

(1) It'll be nice if we can have a table to list all the data types like https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.32.0/google/datastore/v1/datatypes

(2) When I click 'v1', the page content is the GAPIC documentation, right? To be consistent with Ruby and Php, we should have a separate item under 'v1' which is 'DatastoreClient' to have that content. 'v1' should provide an overview. Is it hard to do?

(3) The GAPIC comments are out-dated since we changed the GAPIC entry point. I need to regen for all the APIs that use GAPIC.

**Comment by stephenplusplus** [comment]
> (1) It'll be nice if we can have a table to list all the data types like [googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.32.0/google/datastore/v1/datatypes](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.32.0/google/datastore/v1/datatypes)

In progress 👍 

> (2) When I click 'v1', the page content is the GAPIC documentation, right? To be consistent with Ruby and Php, we should have a separate item under 'v1' which is 'DatastoreClient' to have that content. 'v1' should provide an overview. Is it hard to do?

Would it be possible to get Ruby to conform to this way, which I think is a bit better? Currently, clicking their "v1" lands you on an empty page. If we go forward with your suggestion, what would the overview be?

**Comment by stephenplusplus** [comment]
@swcloud I pushed an update: https://stephenplusplus.github.io/gcloud-node/#/docs/datastore/master/datastore/v1/datastore_client

New:

- Linking works! For example, you can click "AllocateIdsResponse" from https://stephenplusplus.github.io/gcloud-node/#/docs/datastore/master/datastore/v1/datastore_client?method=allocateIds
- Table of Contents on the "Data Types" page
- Method listing on top of the Datastore v1 page (to match our other pages)

**Comment by swcloud** [comment]
For Ruby, they are adding a table of content to fill the blank for V1 menu item.

https://github.com/googleapis/toolkit/pull/1388/files#diff-9c98f244b3240854328ea915b946e635L52
It will just be a table of contents for the services and data types defined under that version

Your suggestion to move GAPIC documentation content to V1 menu item has an issue for an API with multiple services such as PubSub which has PublisherClient and SubscriberClient because we want them to have their own pages and corresponding sub menu items.

Is it easy to do to add a simple TOC for V1 menu item?

**Comment by swcloud** [comment]
@stephenplusplus "Data Types" looks awesome now!

**Comment by stephenplusplus** [comment]
Makes sense. Updates: http://stephenplusplus.github.io/gcloud-node/#/docs/datastore/master/v1

**Comment by swcloud** [comment]
@stephenplusplus That's all we want! Great Job!

BTW, I added another PR to include docs for a few other gapic-based APIs such as logging, pubsub and spanner.

**Pull request merged**
