### PR TITLE
Storage: add https support to getSignedUrl

### PR DESCRIPTION
**Pull request by mziccard**
Added `https` field to getSignedUrl `options` parameter.
If `https` is set the returned url uses HTTPS.
Otherwise we stick to HTTP.

### CODE REVIEW

**Comment by ryanseys** [comment]
You'll have to lint your changes to ensure they meet the requirements. In this case it appears you missed a semi-colon.

Regarding this PR, I'm wondering why we don't just use HTTPS by default. Thoughts @stephenplusplus ?

**Comment by stephenplusplus** [comment]
Always https sounds good to me :+1:

**Comment by mziccard** [comment]
Sounds perfect to me.

**Comment by ryanseys** [comment]
@mziccard Would you mind updating this PR to just use https always? :)

**Comment by mziccard** [comment]
In the end, we just added an 's' :)

**Comment by stephenplusplus** [comment]
Merged via 3ce39f676cf2d7290e0157fd5ef07436d8851989.

Thanks, @mziccard!

**Pull request closed without merging**
