### PR TITLE
remove google-proto-files

### PR DESCRIPTION
**Pull request by stephenplusplus**
## ⚠️ Includes a breaking change for `@google-cloud/common-grpc`

This removes the usage of "google-proto-files" from `@google-cloud/common-grpc`, as well as our APIs. It is still in use by the generated code.

#### To Dos

- [x] Unit tests

#### Status

✔️ Handwritten APIs that load files from "protos" directory:
- Bigtable
- Datastore
- Pub/Sub
- Spanner

❌ Autogen APIs that load files from "google-proto-files" dependency:
- Datastore
- Pub/Sub
- Spanner
- Speech

### CODE REVIEW

**Comment by lukesneeringer** [comment]
Where do the protos live now?

**Comment by stephenplusplus** [comment]
Datastore as an example:
```
packages/
  datastore/
    protos/
      google/
        api/
          **/*.proto
        datastore/
          v1/
            datastore.proto
        protobuf/
          **/*.proto
        type/
          **/*.proto
```

**Comment by callmehiphop** [comment]
What does the process for updating proto files look like now? Are we just essentially copy/pasting?

**Comment by stephenplusplus** [comment]
Yes, I believe that's the plan. @lukesneeringer?

**Comment by lukesneeringer** [comment]
Yep, straight-out copy/paste is the correct thing to do.

**Comment by stephenplusplus** [comment]
@callmehiphop ready for a review! Note that for testing locally, you'll have to run `npm run link-common`, as the updates to the modules depend on the updates to `@google-cloud/common-grpc`

**Comment by stephenplusplus** [comment]
@lukesneeringer RE the "❌ Autogen APIs that load files from "google-proto-files" dependency" section from the first post, who can take care of this? Those generated `_client.js` files will need to load the protos from `../../protos/google/...` (the amount of `../../`s was a guess).

**Comment by callmehiphop** [comment]
@stephenplusplus I'm getting a lot of failures locally for PubSub unit tests

```bash
TypeError: base64 is not a function
      at Function.from (native)
      at Function.from (native)
      at Subscription.formatMessage_ (src/subscription.js:364:31)
      at Function.Subscription.formatMessage_ (test/subscription.js:100:55)
      at src/subscription.js:723:29
      at Array.map (native)
      at src/subscription.js:722:8
      at Object.subscription.parent.request (test/subscription.js:658:9)
      at Subscription.pull (src/subscription.js:704:37)
      at Context.<anonymous> (test/subscription.js:869:22)

```

Not sure if I missed a step or something

**Pull request merged**
