### PR TITLE
docs: added java to language switcher

### LINKED ISSUE #827: Add link to gcloud-java from landing page
gcloud-java needs to be added to the Node.js landing page language-switcher menu (in the top left corner).  Here's the associated logo:
icon-lang-java-duke

### PR DESCRIPTION
**Pull request by callmehiphop**
closes #827 

[demo](http://callmehiphop.github.io/gcloud-node/#/)

### CODE REVIEW

**Comment by jgeewax** [comment]
Screenshot ?

**Comment by callmehiphop** [comment]
@jgeewax whoops! updated my post with a link to a demo

**Comment by jgeewax** [comment]
LGTM :+1:

**Comment by stephenplusplus** [comment]
Nice work, Picasso! :art:

**Pull request merged**
