### PR TITLE
site: update logo

### PR DESCRIPTION
**Pull request by stephenplusplus**
RE: https://github.com/GoogleCloudPlatform/gcloud-common/issues/38

Previews:

screen shot 2015-12-01 at 12 41 15 pm
screen shot 2015-12-01 at 12 41 06 pm

### CODE REVIEW

**Comment by jgeewax** [comment]
Hm I think we want the Google Cloud one, not Google Developers.

logo_lockup_cloud_platform_icon_horizontal

(there's also an .ai file if you guys can handle those...?)

**Comment by stephenplusplus** [comment]
Ah, right. I think we'll need the logo in white. The colors look pretty ick against our blue background. Is that available already, or should we just try to edit it? If you send me the AI, I can give it a go.

**Comment by stephenplusplus** [comment]
:+1: or :-1: 

screen shot 2015-12-01 at 1 52 22 pm

**Comment by stephenplusplus** [comment]
Is there anyone who could make up some dark-background friendly ones? I'm probably the wrong person for this task :) (though we do have @callmehiphop)

**Comment by callmehiphop** [comment]
What was wrong with the old logo icon? I can just put the new text with the old icon

**Comment by stephenplusplus** [comment]
I'm cool with it, just thought it was meant to be updated with the new branding materials.

**Comment by jgeewax** [comment]
Yea - looks like we're dragging our feet a bit on getting new branding
stuff... I'll ping someone and get back to you, but no idea on whether they
have these all packaged up and whatnot.

**Comment by callmehiphop** [comment]
> I'm cool with it, just thought it was meant to be updated with the new branding materials.

Per https://cloud.google.com, it doesn't look like the logo for cloud platform has changed, just the font face?

**Pull request closed without merging**
