### PR TITLE
bigquery: assign record type for nested schemas

### LINKED ISSUE #1422: createTable - Required parameter is missing
I'm creating a table with an existing dataset like this:

```javascript
var bigquery = gcloud.bigquery({
  projectId: 'ionic-stats-storage',
  keyFilename: './bigquery.json'
});

var cliDataset = bigquery.dataset('CLI');
cliDataset.createTable(type, {
        schema: {
          fields: [
            { type: 'string', name: 'type' },
            { type: 'string', name: 'service' },
            { type: 'string', name: 'uuid' },
            { type: 'timestamp', name: 'created_at' },
            { name: 'data', fields: fields }
          ]
        }
      }, function(err, table, apiResponse) {
...
});
```

This is the payload being sent to the `/tables` endpoint as I inspected it in the gcloud node library (pretty-printed):

```json
{
  "schema": {
    "fields": [
      {
        "type": "string",
        "name": "type"
      },
      {
        "type": "string",
        "name": "service"
      },
      {
        "type": "string",
        "name": "uuid"
      },
      {
        "type": "timestamp",
        "name": "created_at"
      },
      {
        "name": "data",
        "fields": [
          {
            "name": "favorite_flavor",
            "type": "string"
          }
        ]
      }
    ]
  },
  "tableReference": {
    "datasetId": "CLI",
    "projectId": "ionic-stats-storage"
  }
}
```

The API is returning a vague error about a missing required parameter, but doesn't say which one, and I believe I'm using the node API correctly (very possible I'm not). Note: I also tried removing the `data` record in case I wasn't doing that properly, but I receive the same response:

```
{ ApiError: Required parameter is missing
    at new util.ApiError (/Users/max/git/ionic-track/node_modules/gcloud/lib/common/util.js:106:10)
    at Object.parseHttpRespBody (/Users/max/git/ionic-track/node_modules/gcloud/lib/common/util.js:184:30)
    at Object.handleResp (/Users/max/git/ionic-track/node_modules/gcloud/lib/common/util.js:124:18)
    at /Users/max/git/ionic-track/node_modules/gcloud/lib/common/util.js:447:12
    at Request.onResponse [as _callback] (/Users/max/git/ionic-track/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/Users/max/git/ionic-track/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/max/git/ionic-track/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
  code: 400,
  errors:
   [ { domain: 'global',
       reason: 'required',
       message: 'Required parameter is missing' } ],
  response: undefined,
  message: 'Required parameter is missing' }
```

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #1422

### CODE REVIEW

**Comment by callmehiphop** [comment]
Looks like there are a few linting issues per Travis.

**Comment by stephenplusplus** [comment]
That was an issue we merged to master. It's fixed now!

**Comment by stephenplusplus** [comment]
Instead of blitzing Travis, I just ran against Node stasble. Feel free to restart the others.

**Comment by callmehiphop** [comment]
Should there be some sort of documentation/example stating we support nested schemas? Or was it already assumed/documented and we just didn't implement it correctly..?

**Comment by stephenplusplus** [comment]
It's more like an implementation detail that only matters if the user didn't know to put it in the right place. Kind of like an API that accepts a "jsonPayload" or "textPayload"-- we detect "did we get an object? Okay, send this as `jsonPayload`". Doesn't matter to the user, they just expect us to do the right thing.

**Comment by callmehiphop** [comment]
Gotcha

**Pull request merged**
